development:
  adapter: mysql2
  database: fooder
  pool: 5
  encoding: utf8
  username: root
  password: root
  host:  localhost

test:
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: fooder
  pool: 5
  encoding: utf8
  username: root
  password: '****'
  host:  localhost
