# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38ae6974ef62a6d30664a057fb2d3b2ffbdffcad5f469eb50af8dd1e6baecd2ab1cea03a611172cf490cb9d3ea461aae95b894227deb49ff251812e8f725ba2f
  paypal_host: https://www.sandbox.paypal.com
  paypal_business_mail: rousseaualexandre.lyon-facilitator@gmail.com

test:
  secret_key_base: 0112fb7330b33d350279c4d6be073756a8cddc4edb65b88676df4cb5e88bd3b846b0035e9e02d22de1d0859f340be7f2c2c9bf0b3ceda4775d20734bb955f574
  paypal_host: https://www.sandbox.paypal.com
  paypal_business_mail: rousseaualexandre.lyon@gmail.com

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  paypal_host: https://www.paypal.com
